#!/bin/bash

#   BAREOS® - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2024-2024 Bareos GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.

#
#  Restore a job using grpc
#

set -e
set -o pipefail
set -u

TestName="$(basename "$(pwd)")"
export TestName

JobName=backup-bareos-fd

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions
#shellcheck source=functions
. functions

start_test

grpc bareos.config.Config/ListCatalogs "{}" | tee "$log_home/catalog.list"
grpc bareos.config.Config/ListJobs "{}" | tee "$log_home/job.list"

jobtypes=$(jq -c '.jobs | map(.type) | unique | .[]' "$log_home/job.list")

echo "$jobtypes"

for type in $jobtypes;
do
    grpc bareos.config.Config/ListJobs "{ \"filters\" : [ { \"type\" : { \"select\" : $type } } ]}" | tee "$log_home/job-$type.list"


    diff <(jq -c ".jobs[] | select(.type == $type) | .name" "$log_home/job.list") <(jq -c ".jobs[] | select(.type == $type) | .name" "$log_home/job-$type.list")
done

grpc bareos.config.Config/ListClients "{}" | tee "$log_home/client.list"

# protobufs json encoding for bytes is base64, so we need to base64 encode
# the names here

grpc bareos.config.Config/GetDefinition "{ \"client\" : { \"name\" : \"$(echo -n "bareos-fd" | base64)\" } }" | tee "$log_home/client.def"

grpc bareos.config.Config/GetDefinition "{ \"job\" : { \"name\" : \"$(echo -n "backup-bareos-fd" | base64)\" } }" | tee "$log_home/job.def"

grpc bareos.config.Config/GetDefinition "{ \"catalog\" : { \"name\" : \"$(echo -n "MyCatalog" | base64)\" } }" | tee "$log_home/catalog.def"

end_test
