#!/bin/bash

#   BAREOS® - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2024-2024 Bareos GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.

#
#  Restore a job using grpc
#

set -e
set -o pipefail
set -u

TestName="$(basename "$(pwd)")"
export TestName

JobName=backup-bareos-fd

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions
#shellcheck source=functions
. functions

start_test

grpc Client/List "{}" | tee "$log_home/client.list"
grpc Client/ListConfigured "{}" | tee "$log_home/client.configured"

BACKUPCLIENT=$(jq -s '.[0].row.name' "$log_home/client.list")
RESTORECLIENT=$(jq '.clients[0].row.name' "$log_home/client.configured")

echo "------"
echo "BackupClient: $BACKUPCLIENT"
echo "RestoreClient: $RESTORECLIENT"
echo "------"

grpc Client/Info "{ \"clientname\" : $BACKUPCLIENT }" | tee "$log_home/client.info"


grpc Restore/ListSessions "{}" | tee "$log_home/sessions.txt"
grpc Restore/Begin '{ "jobids" : [1], "select_parents" : "false"  }' | tee "$log_home/begin.txt"
grpc Restore/ListSessions "{}" | tee "$log_home/sessions.txt"

TOKEN=$(jq ".token" "$log_home/begin.txt")

grpc Restore/ListFiles "{ \"token\" : $TOKEN }" | tee "$log_home/list.txt"
grpc Restore/ChangeDirectory "{ \"token\" : $TOKEN, \"directory\" : \"${BackupDirectory}/weird-files\" }" | tee "$log_home/cd.txt"
grpc Restore/ChangeMarkedStatus "{ \"token\" : $TOKEN, \"regex\" : \".*\", \"mark\": \"true\" }" | tee "$log_home/mark.txt"
grpc Restore/ListFiles "{ \"token\" : $TOKEN }" | tee "$log_home/list2.txt"
grpc Restore/ChangeDirectory "{ \"token\" : $TOKEN, \"directory\" : \"..\" }" | tee "$log_home/cd.txt"
grpc Restore/FinishSelection "{ \"token\" : $TOKEN }" | tee "$log_home/finish.txt"

BSR=$(jq --raw-output ".bootstrappath" "$log_home/finish.txt")

echo "--- BSR BEGIN ---"
cat "${BSR}"
echo "--- BSR END ---"

grpc Restore/ChangeDirectory "{ \"token\" : $TOKEN, \"directory\" : \"..\" }" | tee "$log_home/cd.txt" ||:
grpc Restore/SetOptions  "{ \"token\" : $TOKEN, \"client\" : \"bareos-fd\", \"catalog\" : \"MyCatalog\", \"job\" : \"RestoreFiles\" }"
grpc Restore/Commit "{ \"token\": $TOKEN }"

grpc Restore/Abort "{ \"token\" : $TOKEN }" | tee "$log_home/abort.txt"

end_test
