#!/bin/bash

#   BAREOS® - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2024-2024 Bareos GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.

#
#  Restore a job using grpc
#

set -e
set -o pipefail
set -u

TestName="$(basename "$(pwd)")"
export TestName

JobName=backup-bareos-fd

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions
#shellcheck source=functions
. functions

start_test

grpc bareos.config.Config/ListCatalogs "{}" | tee "$log_home/catalogs.list"

CATALOG=$(jq -c '.catalogs | .[0] | .id' "$log_home/catalogs.list")

DEFAULT_OPTIONS="{ \"range\" : { \"limit\" : 1000 } }"

UNAME_ID=8
UNAME_NAME=new-uname
UNAME_UNAME=new-uname-very-unique
UNAME_AUTOPRUNE=1
UNAME_FILERETENTION=2989
UNAME_JOBRETENTION=343

NAME_ID=9
NAME_NAME=new-name
NAME_UNAME=""
NAME_AUTOPRUNE=0
NAME_FILERETENTION=0
NAME_JOBRETENTION=0

grpc bareos.database.Database/ListClients "{ \"catalog\" : $CATALOG, \"options\" : $DEFAULT_OPTIONS, \"filters\" : [ { \"uname\" : { \"match\" : \"${UNAME_UNAME}\" } } ] }" | tee "$log_home/uname_pre_client.list"
grpc bareos.database.Database/ListClients "{ \"catalog\" : $CATALOG, \"options\" : $DEFAULT_OPTIONS, \"filters\" : [ { \"name\" : { \"match\" : \"${NAME_NAME}\" } } ] }" | tee "$log_home/name_pre_client.list"

cat <<EOF > $tmp/bconcmds
sqlquery
INSERT INTO client (clientid, name, uname, autoprune, fileretention, jobretention)
VALUES (${UNAME_ID}, '${UNAME_NAME}', '${UNAME_UNAME}', ${UNAME_AUTOPRUNE}, ${UNAME_FILERETENTION}, ${UNAME_JOBRETENTION}),
       (${NAME_ID}, '${NAME_NAME}', '${NAME_UNAME}', ${NAME_AUTOPRUNE}, ${NAME_FILERETENTION}, ${NAME_JOBRETENTION});
EOF
run_bconsole

grpc bareos.database.Database/ListClients "{ \"catalog\" : $CATALOG, \"options\" : $DEFAULT_OPTIONS, \"filters\" : [ { \"uname\" : { \"match\" : \"${UNAME_UNAME}\" } } ] }" | tee "$log_home/uname_post_client.list"
grpc bareos.database.Database/ListClients "{ \"catalog\" : $CATALOG, \"options\" : $DEFAULT_OPTIONS, \"filters\" : [ { \"name\" : { \"match\" : \"${NAME_NAME}\" } } ] }" | tee "$log_home/name_post_client.list"

# check that the condition holds
jq -e ".clients | all(.name == \"${NAME_NAME}\")" tmp/testrunner-database/name_post_client.list
# check that we found at least some clients
jq -e ".clients | length | . > 0" tmp/testrunner-database/name_post_client.list
# check that the condition holds
jq -e ".clients | all(.uname == \"${UNAME_UNAME}\")" tmp/testrunner-database/uname_post_client.list
# check that we found at least some clients
jq -e ".clients | length | . > 0" tmp/testrunner-database/uname_post_client.list

grpc bareos.database.Database/ListClients "{ \"catalog\" : $CATALOG, \"options\" : $DEFAULT_OPTIONS }" | tee "$log_home/client.list"

grpc bareos.database.Database/ListJobs "{ \"catalog\" : $CATALOG, \"options\" : $DEFAULT_OPTIONS }" | tee "$log_home/job.list"

end_test
